### ISSUE TITLE
minishift openshift version list displays versions that are not deployable

### ISSUE THREAD

**Issue by eriknelson** [minishift/minishift#1922]
### General information

  * Minishift version: minishift v1.11.0+4459917
  * OS: Fedora 27
  * Hypervisor: KVM

### Steps to reproduce

  1. `minishift openshift version list` displays 3.8/3.9 alphas.
  2. `minishift config set openshift-version v3.9.0-alpha.3`
  3. `minishift delete && minishift start --service-catalog --iso-url centos --show-libmachine-logs -v5`

### Expected

minishift v3.9.0-alpha.3 should be deployed, or have not been listed as an available version.

### Actual

minishift fails to deploy with a 404 error from github, see attached log.

### Logs

[minishift-start.txt](https://gist.github.com/eriknelson/3493b3b59f68e0d9adc6073811ab8ff4)

**Comment by praveenkumar** [comment]
Problem is the way we are getting the version list is from github releases but looks like there is no image available to docker hub for same. We might need to rethink it and use docker tags to show the versions.

**Comment by anjannath** [comment]
Aren't we already fetching the version list from docker hub.

https://github.com/minishift/minishift/blob/master/pkg/minishift/openshift/version/openshift_versions.go#L58

**Comment by praveenkumar** [comment]
@anjannath Ah I meant another way around because of release artifact not available on Github release page but image available on docker hub.

**Comment by praveenkumar** [comment]
@eriknelson FYI, now `v3.9.0-alpha.3` binaries available on GitHub releases so you can try.

**Comment by eriknelson** [comment]
@praveenkumar Thanks! Will give that a try.

**Comment by gbraad** [comment]
There still seems to be an issue with async releasing binaries as containers on docker hub and github releases.

**Comment by sosiouxme** [comment]
The binaries *are* available on the [GitHub release](https://github.com/openshift/origin/releases/tag/v3.9.0-alpha.3). Perhaps they're just not in the format minishift is expecting them? It doesn't tell us what it's trying to do.

**It would be nice if there were a `-v` level that would tell us exactly what it's actually trying to do so we can see where it's going wrong and possible ways to fix / work around.**

As @gbraad helpfully informed me, you can work around this by pre-caching the binary. Just get the oc client one way or another and put it where it will be cached:

```
$ mkdir -p ~/.minishift/cache/oc/v3.9.0-alpha.3/linux/
$ mv ov ~/.minishift/cache/oc/v3.9.0-alpha.3/linux/
```

If you're using `--iso-url centos` as above, you'll further run into the issue that 3.8+ won't run with swap enabled. Container log entry:

```
     F0126 05:00:58.934172    2335 node.go:269] failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. 
/proc/swaps contained: 
[Filename		Type		Size	Used	Priority /dev/sda2                               partition	1023996	0	-1]
```

I'm not sure how to have minishift disable swap on startup (or configure the node to ignore it) so I just went back to using the default. **Could the minishift centos image be updated to disable swap?**

Then, finally, if you get past this, the server panics as in https://github.com/openshift/origin/issues/18298 -- not minishift's fault obviously. Looks like a new tag and build are on the way.

**Comment by eriknelson** [comment]
@sosiouxme Thanks for the heads up. At the time that I posted this, if you look at the [releases page](https://github.com/openshift/origin/releases), v3.9.0-alpha.3 was listed similar to alpha.2 and alpha.1, both of which seem to be visually smaller items? I'm not sure what the significance of this is, but alpha.3 was definitely not available at the endpoint minishift was trying to pull from.

I've been recommending `--iso-url centos` to our addon users because [boot2docker was called out](https://docs.openshift.org/latest/minishift/troubleshooting/troubleshooting-misc.html#authentication-required-to-push-image) as having issues with minishift registry access from Fedora hosts (a requirement for developers working with the Ansible Broker).

I suppose unsurprisingly, [our tooling **does** work with with a boot2docker minishift registry](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle) from a Fedora host, because it's using docker-py 2.5.1 to build and push, rather than the system tools. It sounds like it may be safer to recommend users use the default iso with the caveat that if they stray from the tooling, they're going to have a bad time?

**Comment by gbraad** [comment]
@sosiouxme I saw the same issue as you with swap. Can you file an issue for this, so we can follow-up? This needs to be done in the ISO, as we will always turn swap on. Will see if we can make thi part of the provisioning instead, as this also allows us to toggle and add the skip parameter. I can imagine that in some situations we want swap.

**Comment by gbraad** [comment]
Take note, @eriknelson @sosiouxme boot2docker's support may end within several months. The default in that case will be the `minikube` iso.

**Comment by praveenkumar** [comment]
@sosiouxme Today I was trying to get 3.9.0-alpha.3 binary and looks like I am facing issue https://github.com/openshift/origin/issues/18364 even after downloading the linux tarball for oc binary I am not able to extract it :(

**Comment by eriknelson** [comment]
Seeing this issue crop up again with `v3.9.0-alpha.4`, in case anyone is looking for a repro case.

**Comment by sosiouxme** [comment]
@eriknelson i would watch https://github.com/openshift/origin/issues/18364

**Comment by praveenkumar** [comment]
@eriknelson @sosiouxme issue for `v3.9.0-alpha.3` is resolved and now GitHub has valid binaries. 

Also, today when I tested `v3.9.0-alpha.3` then it no more giving the error about swap enablement. 

```
$ ./minishift start --openshift-version v3.9.0-alpha.3 --iso-url centos
[...]
-- Starting Minishift VM ............... OK
[...]
Starting OpenShift using openshift/origin:v3.9.0-alpha.3 ...
Pulling image openshift/origin:v3.9.0-alpha.3
Pulled 1/4 layers, 26% complete
Pulled 2/4 layers, 59% complete
Pulled 3/4 layers, 89% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.6:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

$ ./minishift openshift version
openshift v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.8
```

**Comment by LalatenduMohanty** [comment]
@eriknelson closing the issue as it is resolved now. You can always ask to re-open the issue if you see this again.

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty I don't think this is properly resolved, so it should be reopened.
These are the tags on Github (not saying they all have binaries)
![image](https://user-images.githubusercontent.com/78350/37026799-c8991a4e-212f-11e8-9de9-432aa08e382c.png)

These are the versions displayed by minishift openshift version list (minishift v1.14.0+1ec5877):
```
minishift openshift version list
The following OpenShift versions are available:
	- v1.4.1
	- v1.5.0
	- v1.5.1
	- v3.10.0
	- v3.10.0-alpha.0
	- v3.6.0
	- v3.6.1
	- v3.7.0
	- v3.7.1
	- v3.8.0-alpha.0
	- v3.8.0-alpha.1
	- v3.9.0
	- v3.9.0-alpha.0
	- v3.9.0-alpha.1
	- v3.9.0-alpha.2
	- v3.9.0-alpha.3
	- v3.9.0-alpha.4
```

As you can see, there's release v3.9.0 which is not in GitHub.

And the v3.8.x don't have binaries in GitHub.

**Comment by LalatenduMohanty** [comment]
@jorgemoralespou you are right. The issues are still there and we are tracking them in https://github.com/minishift/minishift/issues/2069. This issue was closed as it was about a single release and it got fixed from orgin side and the root cause of these two issues are different.
